<?php

declare(strict_types=1);

namespace SumUp\Types;

/**
 * Affiliate metadata for the transaction.
 * It is a field that allow for integrators to track the source of the transaction.
 *
 */
class CreateReaderCheckoutRequestAffiliate
{
    /**
     * Application ID of the affiliate.
     * It is a unique identifier for the application and should be set by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page.
     *
     * @var string
     */
    public string $appId;

    /**
     * Foreign transaction ID of the affiliate.
     * It is a unique identifier for the transaction.
     * It can be used later to fetch the transaction details via the [Transactions API](https://developer.sumup.com/api/transactions/get).
     *
     * @var string
     */
    public string $foreignTransactionId;

    /**
     * Key of the affiliate.
     * It is a unique identifier for the key  and should be generated by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page.
     *
     * @var string
     */
    public string $key;

    /**
     * Additional metadata for the transaction.
     * It is key-value object that can be associated with the transaction.
     *
     * @var array<string, mixed>|null
     */
    public ?array $tags = null;

}
