<?php

declare(strict_types=1);

namespace SumUp\Types;

/**
 * A RFC 9457 problem details object.
 *
 * Additional properties specific to the problem type may be present.
 */
class Problem
{
    /**
     * A URI reference that identifies the problem type.
     *
     * @var string
     */
    public string $type;

    /**
     * A short, human-readable summary of the problem type.
     *
     * @var string|null
     */
    public ?string $title = null;

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     *
     * @var int|null
     */
    public ?int $status = null;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     *
     * @var string|null
     */
    public ?string $detail = null;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     *
     * @var string|null
     */
    public ?string $instance = null;

}
