<?php
// phpcs:ignoreFile
require_once __DIR__ . '/stubs/pos-reader-settings.php';
use WCPOS\WooCommercePOS\SumUpTerminal\Settings;
use WCPOS\WooCommercePOS\SumUpTerminal\Server\Pos_Reader_Settings;
$_GET['section'] = Settings::GATEWAY_ID;
$option = 'woocommerce_pos_settings_payment_gateways';
$GLOBALS['posted'] = array( 'api_key' => 'test', 'default_reader' => 'one', 'allowed_readers' => array( 'one', 'two' ), 'lock_to_default' => 'yes' );
list( $gateway ) = settings_gateway();
expect( 'text' === $gateway->form_fields['default_reader']['type'], 'fields available without Pro' );
expect( $gateway->process_admin_options(), 'gateway saves without Pro' );
expect( 'one' === Settings::get_gateway_settings()['default_reader'] && ! isset( $GLOBALS['options'][ $option ] ), 'no Pro writes only gateway settings' );
expect( class_exists( Pos_Reader_Settings::class ), 'mirror class exists' );
$before = $GLOBALS['options'];
Pos_Reader_Settings::mirror( Settings::get_gateway_settings() );
Pos_Reader_Settings::migrate_once();
expect( $before === $GLOBALS['options'], 'mirror and migration do not write without Pro' );
enable_pro();
$GLOBALS['options'][ $option ] = array( 'gateways' => array( 'other' => array( 'default_reader' => 'other' ), Settings::GATEWAY_ID => array( 'enabled' => true ) ), 'unrelated' => 'keep' );
list( $gateway ) = settings_gateway();
$GLOBALS['posted']['allowed_readers'] = array( 2 => 'one', 5 => '', 8 => 'two', 9 => 7, 10 => false, 11 => null );
expect( $gateway->process_admin_options(), 'parent save result retained' );
$values = array( 'enabled' => true, 'default_reader' => 'one', 'allowed_readers' => array( 'one', 'two' ), 'lock_to_default' => true );
expect( $values === $GLOBALS['options'][ $option ]['gateways'][ Settings::GATEWAY_ID ], 'saved values mirrored with normalized list and effective lock' );
expect( array( 'default_reader' => 'other' ) === $GLOBALS['options'][ $option ]['gateways']['other'] && 'keep' === $GLOBALS['options'][ $option ]['unrelated'], 'other settings untouched' );
$GLOBALS['posted']['default_reader'] = '';
$GLOBALS['posted']['allowed_readers'] = array( 'two' );
$gateway->process_admin_options();
$values['default_reader'] = '';
$values['allowed_readers'] = array( 'two' );
$values['lock_to_default'] = false;
expect( $values === $GLOBALS['options'][ $option ]['gateways'][ Settings::GATEWAY_ID ], 'shrunk list replaces stored list and no-default lock is false' );
$GLOBALS['posted']['allowed_readers'] = array();
$gateway->process_admin_options();
expect( array() === $GLOBALS['options'][ $option ]['gateways'][ Settings::GATEWAY_ID ]['allowed_readers'], 'explicit empty selection clears mirror' );
$GLOBALS['pro'] = false;
$before = $GLOBALS['options'][ $option ];
$GLOBALS['posted']['default_reader'] = 'different';
$gateway->process_admin_options();
expect( $before === $GLOBALS['options'][ $option ], 'unsupported Pro does not mirror save' );
echo "pos-reader-mirror ok\n";
